# Home
GET http://localhost:3333/

###

# Create Event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "An event for programming lovers!",
  "maximumAttendees": 100
}

###

# Register Attendee
POST http://localhost:3333/events/b940da9d-799b-40d8-a588-a27f33e542a8/attendees
Content-Type: application/json

{
  "name": "Eduardo",
  "email": "eduardo@teste.com"
}