# Home
GET http://localhost:3333/

###

# Create Event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "New Event Test",
  "details": "New Event Test Details.",
  "maximumAttendees": 100
}

###

# Register Attendee
POST http://localhost:3333/events/eeff8f07-5dfe-4332-ae53-04ddff1a4517/attendees
Content-Type: application/json

{
  "name": "Eduardo Alexandre",
  "email": "eduardo@test.com"
}

###

# Get Event
GET http://localhost:3333/events/eeff8f07-5dfe-4332-ae53-04ddff1a4517

###

# Get Attendee Badge
GET http://localhost:3333/attendees/1/badge

###

# Check-in
GET http://localhost:3333/attendees/1/check-in

###

# Get Attendees by Event
GET http://localhost:3333/event/eeff8f07-5dfe-4332-ae53-04ddff1a4517/attendees